name: game-platform-dev

services:
    app-dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - app_dev_node_modules:/app/node_modules
        environment:
            NODE_ENV: development
            WATCHPACK_POLLING: "true"
            CHOKIDAR_USEPOLLING: "true"
            CHOKIDAR_INTERVAL: "500"
        stdin_open: true
        tty: true

volumes:
    app_dev_node_modules:
